export type RiskMemoryKeywordCategory =
  | "deliveryLifecycle"
  | "engineeringWorkflow"
  | "incidents"
  | "infraPlatform"
  | "tradingRiskDomain"
  | "integrations"
  | "featureProjects"
  | "timeMarkers"
  | "actionVerbs";

export type RiskMemoryKeywordDictionary = Record<RiskMemoryKeywordCategory, readonly string[]>;

/**
 * Risk tribe memory keywords.
 *
 * Notes:
 * - Terms are grouped by operational category to keep weighting explainable.
 * - Indonesian + English variants are intentionally duplicated for robust matching.
 * - Keep this dictionary practical (high-signal ops language), not exhaustive jargon soup.
 */
export const RISK_MEMORY_KEYWORDS: RiskMemoryKeywordDictionary = {
  deliveryLifecycle: [
    "delivery",
    "rilis",
    "release",
    "rollout",
    "go live",
    "go-live",
    "deploy",
    "deployment",
    "redeploy",
    "ship",
    "staging",
    "production",
    "prod",
    "uat",
    "sit",
    "rc",
    "smoke test",
    "regression",
    "qa signoff",
    "signoff",
    "cutoff",
    "eta",
    "deadline",
    "target date",
    "roll back",
    "rollback",
    "post release",
  ],

  engineeringWorkflow: [
    "ticket",
    "task",
    "story",
    "epic",
    "scope",
    "acceptance criteria",
    "ac",
    "backlog",
    "sprint",
    "standup",
    "retro",
    "grooming",
    "pr",
    "mr",
    "merge request",
    "code review",
    "reviewer",
    "approve",
    "approval",
    "commit",
    "branch",
    "cherry pick",
    "hotfix",
    "patch",
    "refactor",
    "unit test",
    "integration test",
    "e2e",
  ],

  incidents: [
    "incident",
    "insiden",
    "outage",
    "down",
    "downtime",
    "error",
    "fatal",
    "panic",
    "crash",
    "fail",
    "gagal",
    "failed",
    "timeout",
    "latency",
    "degraded",
    "slow",
    "stuck",
    "blocker",
    "critical",
    "urgent",
    "sev1",
    "sev2",
    "root cause",
    "rca",
    "postmortem",
  ],

  infraPlatform: [
    "infra",
    "infrastructure",
    "platform",
    "service",
    "api",
    "gateway",
    "proxy",
    "queue",
    "worker",
    "cron",
    "job",
    "scheduler",
    "cache",
    "redis",
    "kafka",
    "database",
    "db",
    "sql",
    "query",
    "migration",
    "schema",
    "index",
    "kubernetes",
    "k8s",
    "docker",
    "pod",
    "helm",
    "nginx",
    "grafana",
    "sentry",
  ],

  tradingRiskDomain: [
    "trading",
    "risk",
    "broker",
    "execution",
    "order",
    "fill",
    "slippage",
    "liquidity",
    "lp",
    "provider",
    "dealer",
    "dealing",
    "quote",
    "pricing",
    "price feed",
    "symbol",
    "instrument",
    "lot",
    "leverage",
    "margin",
    "exposure",
    "hedging",
    "hedge",
    "spread",
    "swap",
    "trailing",
    "volatility",
    "price gap",
    "trade lock",
    "holiday session",
  ],

  integrations: [
    "integration",
    "integrasi",
    "webhook",
    "callback",
    "sync",
    "sinkron",
    "mapping",
    "adapter",
    "connector",
    "payload",
    "schema mismatch",
    "contract",
    "api key",
    "secret",
    "token",
    "person_id",
    "disable person_id",
    "feishu",
    "lark",
    "jira",
    "gitlab",
    "openclaw",
  ],

  featureProjects: [
    "group trade",
    "trigger amb",
    "lp mapping",
    "maker pools",
    "maker-pools",
    "trade lock",
    "price gap",
    "spread",
    "swap",
    "trailing",
    "profile assessment",
    "symbol alignment",
    "holiday session",
    "volatility",
    "disable person_id",
    "oz upgrade",
  ],

  timeMarkers: [
    "hari ini",
    "besok",
    "lusa",
    "minggu ini",
    "minggu depan",
    "bulan ini",
    "sekarang",
    "barusan",
    "tadi",
    "malam ini",
    "pagi ini",
    "siang ini",
    "sore ini",
    "tonight",
    "today",
    "tomorrow",
    "this week",
    "next week",
    "asap",
    "eod",
    "end of day",
    "now",
    "soon",
    "eta",
    "jam",
    "wib",
    "utc",
  ],

  actionVerbs: [
    "cek",
    "check",
    "follow up",
    "follow-up",
    "monitor",
    "investigate",
    "investigasi",
    "fix",
    "perbaiki",
    "patch",
    "rollback",
    "roll back",
    "deploy",
    "release",
    "validate",
    "verifikasi",
    "confirm",
    "konfirmasi",
    "assign",
    "handover",
    "escalate",
    "eskalasi",
    "need update",
    "need owner",
    "please update",
    "tolong",
    "urgent check",
  ],
};

/**
 * Category weights for NO_REPLY high-signal memory capture.
 * Higher weight => stronger evidence of operational significance.
 */
export const RISK_MEMORY_CATEGORY_WEIGHTS: Record<RiskMemoryKeywordCategory, number> = {
  featureProjects: 6,
  tradingRiskDomain: 4,
  incidents: 4,
  deliveryLifecycle: 3,
  infraPlatform: 3,
  integrations: 3,
  engineeringWorkflow: 2,
  timeMarkers: 1,
  actionVerbs: 1,
};
